// Drift Data Access Object for the custom_fields table.
//
// CustomFieldsDao provides all database operations for the CustomFields table.
// The repository implementation (CustomFieldRepositoryImpl) delegates to this DAO.
//
// Key design choices:
// - Soft-delete pattern: softDeleteField() sets deletedAt to now; no hard deletes
// - getActiveForProfile() filters by profileId AND deletedAt IS NULL
// - insertOnConflictUpdate handles both create and update (upsert)
//
// Requirements: PROF-07, PROF-08, PROF-09
import 'package:drift/drift.dart';

import '../app_database.dart';
import '../tables/custom_fields_table.dart';

// Generated by build_runner: run `flutter pub run build_runner build`
part 'custom_fields_dao.g.dart';

/// Drift DAO for reading and writing custom fields.
///
/// Obtain an instance via [AppDatabase.customFieldsDao].
@DriftAccessor(tables: [CustomFields])
class CustomFieldsDao extends DatabaseAccessor<AppDatabase>
    with _$CustomFieldsDaoMixin {
  CustomFieldsDao(super.db);

  /// Returns all active (non-deleted) custom fields for a given profile.
  ///
  /// Results are ordered by createdAt ascending (stable insertion order).
  Future<List<CustomField>> getActiveForProfile(String profileId) {
    return (select(customFields)
          ..where((f) => f.profileId.equals(profileId) & f.deletedAt.isNull())
          ..orderBy([(f) => OrderingTerm.asc(f.createdAt)]))
        .get();
  }

  /// Inserts or replaces a custom field row (conflict target: primary key).
  ///
  /// Use this for both create and update.
  Future<void> upsertField(CustomFieldsCompanion companion) {
    return into(customFields).insertOnConflictUpdate(companion);
  }

  /// Soft-deletes a custom field by setting its deletedAt timestamp.
  ///
  /// Does not hard-delete the row. The row remains readable via direct selects
  /// but is excluded from [getActiveForProfile].
  Future<void> softDeleteField(String id) {
    return (update(customFields)..where((f) => f.id.equals(id))).write(
      CustomFieldsCompanion(
        deletedAt: Value(DateTime.now().toUtc()),
        updatedAt: Value(DateTime.now().toUtc()),
      ),
    );
  }
}
