// Drift Data Access Object for the profiles table.
//
// ProfilesDao provides all database operations for the Profiles table.
// The repository implementation (ProfileRepositoryImpl) delegates to this DAO.
//
// Key design choices:
// - Soft-delete pattern: softDelete() sets deletedAt to now; no hard deletes
// - watchActiveProfiles() uses a WHERE deletedAt IS NULL filter
// - insertOnConflictUpdate handles both create and update (upsert)
//
// Requirements: PROF-01, PROF-02, PROF-03
import 'package:drift/drift.dart';

import '../app_database.dart';
import '../tables/custom_fields_table.dart';
import '../tables/profiles_table.dart';

// Generated by build_runner: run `flutter pub run build_runner build`
part 'profiles_dao.g.dart';

/// Drift DAO for reading and writing profiles.
///
/// Obtain an instance via [AppDatabase.profilesDao].
@DriftAccessor(tables: [Profiles, CustomFields])
class ProfilesDao extends DatabaseAccessor<AppDatabase>
    with _$ProfilesDaoMixin {
  ProfilesDao(super.db);

  /// Returns a live stream of all non-deleted profiles, ordered by displayName.
  ///
  /// Emits a new list whenever a profile row changes (insert, update, delete).
  Stream<List<Profile>> watchActiveProfiles() {
    return (select(profiles)
          ..where((p) => p.deletedAt.isNull())
          ..orderBy([(p) => OrderingTerm.asc(p.displayName)]))
        .watch();
  }

  /// Returns the count of non-deleted profiles.
  Future<int> countActive() async {
    final countExpr = profiles.id.count();
    final query = selectOnly(profiles)
      ..addColumns([countExpr])
      ..where(profiles.deletedAt.isNull());
    final row = await query.getSingle();
    return row.read(countExpr) ?? 0;
  }

  /// Inserts or replaces a profile row (conflict target: primary key).
  ///
  /// Use this for both create and update. Set all mutable fields; leave
  /// system fields (id, createdAt) unchanged on updates.
  Future<void> upsertProfile(ProfilesCompanion companion) {
    return into(profiles).insertOnConflictUpdate(companion);
  }

  /// Soft-deletes a profile by setting its deletedAt timestamp.
  ///
  /// Does not hard-delete the row. The row remains readable via direct
  /// selects but is excluded from [watchActiveProfiles] and [countActive].
  Future<void> softDelete(String id) {
    return (update(profiles)..where((p) => p.id.equals(id))).write(
      ProfilesCompanion(
        deletedAt: Value(DateTime.now().toUtc()),
        updatedAt: Value(DateTime.now().toUtc()),
      ),
    );
  }

  /// Returns a single profile by [id], or null if not found.
  Future<Profile?> getProfileById(String id) {
    return (select(profiles)..where((p) => p.id.equals(id))).getSingleOrNull();
  }

  /// Returns all active profiles as a plain list (non-streaming).
  Future<List<Profile>> getActiveProfiles() {
    return (select(profiles)..where((p) => p.deletedAt.isNull())).get();
  }
}
