// Authentication state provider — SEC-04.
//
// AuthStateNotifier manages whether the app is currently locked or unlocked.
// It starts locked on every cold start so profile data is never visible
// without authentication.
//
// keepAlive: true — auth state must survive provider disposal cycles;
// losing unlocked state would cause spurious re-prompts.
//
// Requirements: SEC-04 (profile data never visible without authentication)

import 'package:riverpod_annotation/riverpod_annotation.dart';

// Generated by build_runner: run `flutter pub run build_runner build`
part 'auth_providers.g.dart';

/// Whether the app is currently locked or unlocked.
///
/// The app starts in [locked] state on every cold start.
/// After a successful biometric or PIN authentication the state moves to
/// [unlocked] and go_router redirects the user to /profiles.
enum AuthState { locked, unlocked }

/// Manages the app-level authentication state.
///
/// Usage:
///   // Read current state:
///   final state = ref.watch(authStateNotifierProvider);
///
///   // Trigger unlock (call after local_auth authenticate() returns true):
///   ref.read(authStateNotifierProvider.notifier).unlock();
///
///   // Lock again (call on explicit sign-out or background lock):
///   ref.read(authStateNotifierProvider.notifier).lock();
@Riverpod(keepAlive: true)
class AuthStateNotifier extends _$AuthStateNotifier {
  @override
  AuthState build() => AuthState.locked;

  /// Transitions the app to the unlocked state.
  ///
  /// Call after `local_auth.authenticate()` returns true.
  void unlock() => state = AuthState.unlocked;

  /// Transitions the app back to the locked state.
  ///
  /// Call on explicit sign-out or when a background lock timer fires.
  void lock() => state = AuthState.locked;
}
