// Riverpod providers for AppDatabase and repository instances.
//
// appDatabaseProvider: opens the encrypted Drift database exactly once per
// app session (keepAlive: true). Uses KeyManager to retrieve the encryption
// key from Android Keystore before opening the database.
//
// profileRepositoryProvider / customFieldRepositoryProvider: wraps the
// concrete repository implementations; depends on appDatabaseProvider.
//
// Usage:
//   final db = await ref.watch(appDatabaseProvider.future);
//   final repo = await ref.watch(profileRepositoryProvider.future);
//
// Requirements: SEC-04 (key retrieval before DB open)
import 'dart:io';

import 'package:drift/drift.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../data/database/app_database.dart';
import '../data/repositories/custom_field_repository_impl.dart';
import '../data/repositories/profile_repository_impl.dart';
import '../data/security/key_manager.dart';
import '../domain/repositories/custom_field_repository.dart';
import '../domain/repositories/profile_repository.dart';

// Generated by build_runner: run `flutter pub run build_runner build`
part 'database_provider.g.dart';

/// Riverpod provider for the encrypted [AppDatabase].
///
/// Opens the database exactly once per app session (keepAlive: true).
/// Retrieves the encryption key from Android Keystore via [KeyManager]
/// before calling [openEncryptedDatabase].
///
/// On widget disposal, the database is closed via [ref.onDispose].
@Riverpod(keepAlive: true)
Future<AppDatabase> appDatabase(Ref ref) async {
  const secureStorage = FlutterSecureStorage(
    aOptions: AndroidOptions(encryptedSharedPreferences: false),
  );
  final keyManager = KeyManager(secureStorage);
  final passphrase = await keyManager.getOrCreateKey();

  final dbFolder = await getApplicationDocumentsDirectory();
  final dbFile = File(p.join(dbFolder.path, 'autofill.db'));

  final db = AppDatabase(openEncryptedDatabase(passphrase, dbFile));
  ref.onDispose(db.close);
  return db;
}

/// Riverpod provider for [ProfileRepository].
///
/// Depends on [appDatabaseProvider]. keepAlive matches the DB lifetime.
@Riverpod(keepAlive: true)
Future<ProfileRepository> profileRepository(Ref ref) async {
  final db = await ref.watch(appDatabaseProvider.future);
  return ProfileRepositoryImpl(db);
}

/// Riverpod provider for [CustomFieldRepository].
///
/// Depends on [appDatabaseProvider]. keepAlive matches the DB lifetime.
@Riverpod(keepAlive: true)
Future<CustomFieldRepository> customFieldRepository(Ref ref) async {
  final db = await ref.watch(appDatabaseProvider.future);
  return CustomFieldRepositoryImpl(db);
}
