// Phase 1 stub entitlement provider.
//
// Phase 4 replaces this with a RevenueCat SDK-backed implementation via
// Riverpod's overrideWith — no other code needs to change at Phase 4.
//
// Requirements: PROF-06 (freemium cap enforced in ProfileUseCase)

import 'package:riverpod_annotation/riverpod_annotation.dart';

// Generated by build_runner: run `flutter pub run build_runner build`
part 'entitlement_providers.g.dart';

/// User entitlement tier — controls feature gating (e.g. profile cap).
///
/// Phase 1 stub always returns [EntitlementTier.free]. Phase 4 will
/// replace this provider with a RevenueCat-backed implementation.
enum EntitlementTier { free, paid }

/// Phase 1 stub — always returns [EntitlementTier.free].
///
/// Phase 4 replaces this with a real RevenueCat-backed implementation
/// using Riverpod's [ProviderContainer.overrideWith]. No other code
/// needs to change when Phase 4 lands.
@Riverpod(keepAlive: true)
EntitlementTier entitlementTier(Ref ref) {
  return EntitlementTier.free; // Always free in Phase 1
}
