// Riverpod providers for ProfileUseCase, CustomFieldUseCase, and the profile
// list stream.
//
// These providers are the UI layer's entry point:
//   - profileListProvider: subscribe for a reactive list of active profiles
//   - profileUseCaseProvider: call for profile mutations (create/update/delete)
//   - customFieldUseCaseProvider: call for custom field mutations
//
// Requirements: PROF-01, PROF-02, PROF-03 (profile CRUD via use case)
//               PROF-07, PROF-08, PROF-09 (custom field CRUD via use case)

import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../domain/models/profile.dart';
import '../domain/use_cases/custom_field_use_case.dart';
import '../domain/use_cases/profile_use_case.dart';
import 'database_provider.dart';
import 'entitlement_providers.dart';

// Generated by build_runner: run `flutter pub run build_runner build`
part 'profile_providers.g.dart';

/// Live stream of active (non-deleted) profiles, sorted by displayName.
///
/// Emits a new list whenever any profile is inserted, updated, or soft-deleted.
/// UI widgets that display a profile list should subscribe via:
///   ref.watch(profileListProvider)
@riverpod
Stream<List<FamilyProfile>> profileList(Ref ref) async* {
  final repo = await ref.watch(profileRepositoryProvider.future);
  yield* repo.watchActive();
}

/// Use case provider for profile mutations.
///
/// keepAlive: true — the use case has no disposable resources and should
/// remain alive for the app session.
///
/// Usage:
///   final useCase = await ref.read(profileUseCaseProvider.future);
///   await useCase.createProfile(request);
@Riverpod(keepAlive: true)
Future<ProfileUseCase> profileUseCase(Ref ref) async {
  final repo = await ref.watch(profileRepositoryProvider.future);
  final tier = ref.watch(entitlementTierProvider);
  return ProfileUseCase(repo, tier);
}

/// Use case provider for custom field mutations.
///
/// keepAlive: true — the use case has no disposable resources and should
/// remain alive for the app session.
///
/// Usage:
///   final useCase = await ref.read(customFieldUseCaseProvider.future);
///   await useCase.addField(profileId, label, type);
@Riverpod(keepAlive: true)
Future<CustomFieldUseCase> customFieldUseCase(Ref ref) async {
  final repo = await ref.watch(customFieldRepositoryProvider.future);
  return CustomFieldUseCase(repo);
}
