// Domain model for a user-defined custom field on a profile.
//
// CustomField is the immutable, freezed representation used in the domain
// and UI layers. It mirrors the CustomFields Drift table but is decoupled
// from the database — the repository layer maps Drift rows to/from this model.
//
// Requirements: PROF-07, PROF-08, PROF-09
import 'package:freezed_annotation/freezed_annotation.dart';

import '../../data/database/tables/custom_fields_table.dart';
export '../../data/database/tables/custom_fields_table.dart' show CustomFieldType;

// Generated by freezed: run `flutter pub run build_runner build`
part 'custom_field.freezed.dart';

/// Immutable domain model for a user-defined custom field on a profile.
///
/// All fields mirror [CustomFields] Drift table columns.
/// Obtain instances via [CustomFieldRepository].
@freezed
abstract class CustomField with _$CustomField {
  const factory CustomField({
    required String id,
    required String profileId,
    required String label,
    required CustomFieldType fieldType,
    String? value,
    required DateTime createdAt,
    required DateTime updatedAt,
    DateTime? deletedAt,
    required bool synchronized,
  }) = _CustomField;
}
