// Domain model for a family member profile.
//
// FamilyProfile is the immutable, freezed representation used in the domain
// and UI layers. It mirrors the Profiles Drift table but is decoupled from
// the database — the repository layer maps Drift rows to/from this model.
//
// ProfileCreateRequest and ProfileUpdateRequest are value objects for
// repository write operations; they exclude system-managed fields (id,
// createdAt, updatedAt, deletedAt, synchronized).
//
// Requirements: PROF-01, PROF-02, PROF-03, PROF-04, PROF-05
import 'package:freezed_annotation/freezed_annotation.dart';

import '../../data/database/tables/profiles_table.dart';

// Generated by freezed: run `flutter pub run build_runner build`
part 'profile.freezed.dart';

/// Immutable domain model for a family member profile.
///
/// All fields mirror [Profiles] Drift table columns.
/// Obtain instances via [ProfileRepository].
@freezed
abstract class FamilyProfile with _$FamilyProfile {
  const factory FamilyProfile({
    required String id,
    required String displayName,
    String? dateOfBirth,
    String? addressLine1,
    String? addressLine2,
    String? city,
    String? stateProvince,
    String? postalCode,
    String? country,
    String? phone,
    String? allergies,
    String? emergencyContactName,
    String? emergencyContactPhone,
    required RelationshipTag relationshipTag,
    String? avatarPath,
    required DateTime createdAt,
    required DateTime updatedAt,
    DateTime? deletedAt,
    required bool synchronized,
  }) = _FamilyProfile;
}

/// Value object for creating a new profile.
///
/// Only user-supplied fields — id, createdAt, updatedAt, synchronized are
/// assigned by the repository layer.
@freezed
abstract class ProfileCreateRequest with _$ProfileCreateRequest {
  const factory ProfileCreateRequest({
    required String displayName,
    String? dateOfBirth,
    String? addressLine1,
    String? addressLine2,
    String? city,
    String? stateProvince,
    String? postalCode,
    String? country,
    String? phone,
    String? allergies,
    String? emergencyContactName,
    String? emergencyContactPhone,
    required RelationshipTag relationshipTag,
    String? avatarPath,
  }) = _ProfileCreateRequest;
}

/// Value object for updating an existing profile.
///
/// All mutable user-facing fields are optional (Value<T>-style or nullable).
/// The repository sets updatedAt = DateTime.now() on every update.
@freezed
abstract class ProfileUpdateRequest with _$ProfileUpdateRequest {
  const factory ProfileUpdateRequest({
    required String id,
    String? displayName,
    String? dateOfBirth,
    String? addressLine1,
    String? addressLine2,
    String? city,
    String? stateProvince,
    String? postalCode,
    String? country,
    String? phone,
    String? allergies,
    String? emergencyContactName,
    String? emergencyContactPhone,
    RelationshipTag? relationshipTag,
    String? avatarPath,
  }) = _ProfileUpdateRequest;
}
